### ISSUE TITLE
Flying bug

### ISSUE THREAD

**Issue by johnvo0918** [Leprawel/Parkour-controller-script#1]
In the file you provided on GitHub. I can't look up or down. When I changed the camera script to allow looking up and down, when I look up and hold W the player character will just fly. It does the same if you look down and hold S. I figured a fix but when I jump or climb it will do the same if I repeat the above. 
Apparently, it was fixed in your demo from the google drive but I can't find the script for it in the drive.

**Comment by Leprawel** [comment]
I know some people have set the script up to work, so its possible. Maybe one day Ill make a tutorial on it but for now I dont offer any detailed advice. You have to read the script and figure stuff out on your own.
